# Generated by Django 5.2 on 2025-05-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Céréales', 'Céréales'), ('Fruits', 'Fruits'), ('Légumineuses et oléagineux', 'Légumineuses et oléagineux'), ('Cultures industrielles', 'Cultures industrielles'), ('Tubercules et racines', 'Tubercules et racines'), ('Légumes', 'Légumes')], help_text='Choisir une catégorie parmi la liste standard', max_length=50, unique=True, verbose_name='Catégorie'),
        ),
    ]
