# Generated by Django 5.2 on 2025-05-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Légumes', 'Légumes'), ('Céréales', 'Céréales'), ('Fruits', 'Fruits'), ('Cultures industrielles', 'Cultures industrielles'), ('Légumineuses et oléagineux', 'Légumineuses et oléagineux'), ('Tubercules et racines', 'Tubercules et racines')], help_text='Choisir une catégorie parmi la liste standard', max_length=50, unique=True, verbose_name='Catégorie'),
        ),
    ]
