# Generated by Django 5.2 on 2025-05-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Céréales', 'Céréales'), ('Tubercules et racines', 'Tubercules et racines'), ('Légumineuses et oléagineux', 'Légumineuses et oléagineux'), ('Cultures industrielles', 'Cultures industrielles'), ('Légumes', 'Légumes'), ('Fruits', 'Fruits')], help_text='Choisir une catégorie parmi la liste standard', max_length=50, unique=True, verbose_name='Catégorie'),
        ),
    ]
