# Generated by Django 4.2.21 on 2025-05-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Céréales', 'Céréales'), ('Fruits', 'Fruits'), ('Tubercules et racines', 'Tubercules et racines'), ('Légumes', 'Légumes'), ('Légumineuses et oléagineux', 'Légumineuses et oléagineux'), ('Cultures industrielles', 'Cultures industrielles')], help_text='Choisir une catégorie parmi la liste standard', max_length=50, unique=True, verbose_name='Catégorie'),
        ),
    ]
