# Generated by Django 4.2.21 on 2025-05-11 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Cultures industrielles', 'Cultures industrielles'), ('Céréales', 'Céréales'), ('Tubercules et racines', 'Tubercules et racines'), ('Légumineuses et oléagineux', 'Légumineuses et oléagineux'), ('Fruits', 'Fruits'), ('Légumes', 'Légumes')], help_text='Choisir une catégorie parmi la liste standard', max_length=50, unique=True, verbose_name='Catégorie'),
        ),
    ]
