# Generated by Django 4.2.21 on 2025-05-12 11:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_batch_exchangerequest_invoice_notification_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name': 'Lot', 'verbose_name_plural': 'Lots'},
        ),
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'verbose_name': 'Profil client', 'verbose_name_plural': 'Profils clients'},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Livraison', 'verbose_name_plural': 'Livraisons'},
        ),
        migrations.AlterModelOptions(
            name='exchangerequest',
            options={'verbose_name': "Demande d'échange", 'verbose_name_plural': "Demandes d'échange"},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Facture', 'verbose_name_plural': 'Factures'},
        ),
        migrations.AlterModelOptions(
            name='loyaltyprogram',
            options={'verbose_name': 'Programme de fidélité', 'verbose_name_plural': 'Programmes de fidélité'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Commande', 'verbose_name_plural': 'Commandes'},
        ),
        migrations.AlterModelOptions(
            name='orderline',
            options={'verbose_name': 'Ligne de commande', 'verbose_name_plural': 'Lignes de commande'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
        migrations.AlterModelOptions(
            name='paymentlog',
            options={'verbose_name': 'Journal de paiement', 'verbose_name_plural': 'Journaux de paiement'},
        ),
        migrations.AlterModelOptions(
            name='productdiscount',
            options={'verbose_name': 'Remise produit', 'verbose_name_plural': 'Remises produit'},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'verbose_name': 'Avis produit', 'verbose_name_plural': 'Avis produits'},
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'Code promo', 'verbose_name_plural': 'Codes promo'},
        ),
        migrations.AlterModelOptions(
            name='proof',
            options={'verbose_name': 'Preuve de livraison', 'verbose_name_plural': 'Preuves de livraison'},
        ),
        migrations.AlterModelOptions(
            name='refundrequest',
            options={'verbose_name': 'Demande de remboursement', 'verbose_name_plural': 'Demandes de remboursement'},
        ),
        migrations.AlterModelOptions(
            name='returnrequest',
            options={'verbose_name': 'Demande de retour', 'verbose_name_plural': 'Demandes de retour'},
        ),
        migrations.AlterModelOptions(
            name='stockalert',
            options={'verbose_name': 'Alerte de stock', 'verbose_name_plural': 'Alertes de stock'},
        ),
        migrations.AlterModelOptions(
            name='stocklevel',
            options={'verbose_name': 'Niveau de stock', 'verbose_name_plural': 'Niveaux de stock'},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'verbose_name': 'Mouvement de stock', 'verbose_name_plural': 'Mouvements de stock'},
        ),
        migrations.AlterModelOptions(
            name='trackinginfo',
            options={'verbose_name': 'Info de suivi', 'verbose_name_plural': 'Infos de suivi'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Entrepôt', 'verbose_name_plural': 'Entrepôts'},
        ),
        migrations.AlterField(
            model_name='batch',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'expiration"),
        ),
        migrations.AlterField(
            model_name='batch',
            name='lot_number',
            field=models.CharField(max_length=50, verbose_name='Numéro de lot'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='api.product', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_client', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_agriculteur',
            field=models.BooleanField(default=False, verbose_name='Agriculteur'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_livreur',
            field=models.BooleanField(default=False, verbose_name='Livreur'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Vérifié'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='language',
            field=models.CharField(default='fr', max_length=5, verbose_name='Langue'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créée le'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='deliverer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Livreur'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='api.order', verbose_name='Commande'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='api.product', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='type',
            field=models.CharField(choices=[('LIVRAISON', 'Problème de livraison'), ('STOCK', 'Intervention stock'), ('REMBOURSEMENT', 'Suivi remboursement'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
        migrations.AlterField(
            model_name='exchangerequest',
            name='replacement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echanges', to='api.product', verbose_name='Produit de remplacement'),
        ),
        migrations.AlterField(
            model_name='exchangerequest',
            name='return_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='echange', to='api.returnrequest', verbose_name='Demande de retour'),
        ),
        migrations.AlterField(
            model_name='exchangerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('COMPLETED', 'Terminé')], default='PENDING', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issued_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Émise le'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='api.order', verbose_name='Commande'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='pdf',
            field=models.FileField(upload_to='invoices/', verbose_name='Fichier PDF'),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty', to='api.clientprofile', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='points',
            field=models.PositiveIntegerField(default=0, verbose_name='Points'),
        ),
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='transactions',
            field=models.JSONField(blank=True, default=list, verbose_name='Transactions'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créée le'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Lien'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Lu'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='api.clientprofile', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('EN_COURS', 'En cours'), ('DELIVERED', 'Livrée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_commandes', to='api.order', verbose_name='Commande'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commandes', to='api.product', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CARD', 'Carte bancaire'), ('BANK', 'Virement'), ('MOBILE', 'Mobile Money'), ('PAYPAL', 'PayPal'), ('APPLE_PAY', 'Apple Pay'), ('GOOGLE_PAY', 'Google Pay')], max_length=20, verbose_name='Moyen de paiement'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.order', verbose_name='Commande'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payé le'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('PAID', 'Payé'), ('FAILED', 'Échoué')], default='PENDING', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='attempt_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tentative le'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='info',
            field=models.JSONField(blank=True, default=dict, verbose_name='Info'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_logs', to='api.order', verbose_name='Commande'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='status',
            field=models.CharField(max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='api.category', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='% de remise'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remises', to='api.product', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.clientprofile', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.product', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='verified_purchase',
            field=models.BooleanField(default=False, verbose_name='Achat vérifié'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='% de remise'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Limite d'utilisation"),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='valid_from',
            field=models.DateTimeField(verbose_name='Valide à partir de'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='valid_to',
            field=models.DateTimeField(verbose_name="Valide jusqu'à"),
        ),
        migrations.AlterField(
            model_name='proof',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='api.delivery', verbose_name='Livraison'),
        ),
        migrations.AlterField(
            model_name='proof',
            name='image',
            field=models.ImageField(upload_to='delivery_proofs/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='proof',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Uploadé le'),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='evidence',
            field=models.FileField(upload_to='refunds/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png'])], verbose_name='Pièce justificative'),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='api.order', verbose_name='Commande'),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Traité le'),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='reason',
            field=models.TextField(verbose_name='Motif'),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Demandé le'),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approuvé'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='order_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_retour', to='api.orderline', verbose_name='Ligne de commande'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Traité le'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='reason',
            field=models.TextField(verbose_name='Motif'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Demandé le'),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.product', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='threshold',
            field=models.PositiveIntegerField(verbose_name='Seuil'),
        ),
        migrations.AlterField(
            model_name='stocklevel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux_stock', to='api.product', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='stocklevel',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='stocklevel',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux_stock', to='api.warehouse', verbose_name='Entrepôt'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='api.batch', verbose_name='Lot'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Entrée'), ('OUT', 'Sortie'), ('ADJ', 'Ajustement')], max_length=3, verbose_name='Type de mouvement'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_stock', to='api.product', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date et heure'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_stock', to='api.warehouse', verbose_name='Entrepôt'),
        ),
        migrations.AlterField(
            model_name='trackinginfo',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_infos', to='api.delivery', verbose_name='Livraison'),
        ),
        migrations.AlterField(
            model_name='trackinginfo',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Localisation'),
        ),
        migrations.AlterField(
            model_name='trackinginfo',
            name='status',
            field=models.CharField(max_length=50, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='trackinginfo',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Horodatage'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Localisation'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
    ]
