# Generated by Django 4.2.21 on 2025-05-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_batch_options_alter_clientprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_client',
            field=models.BooleanField(default=False, verbose_name='Client'),
        ),
    ]
