# Generated by Django 4.2.21 on 2025-05-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_customuser_is_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Mouvement de stock', 'verbose_name_plural': 'Mouvements de stock'},
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='status',
        ),
        migrations.RemoveField(
            model_name='exchangerequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='paymentlog',
            name='status',
        ),
        migrations.RemoveField(
            model_name='refundrequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='trackinginfo',
            name='status',
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_status',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut livraison'),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='exchange_status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('COMPLETED', 'Terminé')], default='PENDING', max_length=20, verbose_name='Statut échange'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('EN_COURS', 'En cours'), ('DELIVERED', 'Livrée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20, verbose_name='Statut commande'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('PAID', 'Payé'), ('FAILED', 'Échoué')], default='PENDING', max_length=20, verbose_name='Statut paiement'),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='payment_status',
            field=models.CharField(default=0, max_length=20, verbose_name='Statut paiement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='refund_status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=20, verbose_name='Statut remboursement'),
        ),
        migrations.AddField(
            model_name='trackinginfo',
            name='tracking_status',
            field=models.CharField(default=0, max_length=50, verbose_name='Statut des suivis'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantité'),
        ),
    ]
