# Generated by Django 4.2.21 on 2025-05-22 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_stockalert_user_alter_customuser_phone_cart_cartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Panier', 'verbose_name_plural': 'Paniers'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Ligne de panier', 'verbose_name_plural': 'Lignes de panier'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Panier', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
