# Generated by Django 4.2.21 on 2025-05-23 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_product_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('agriculteur', models.ForeignKey(blank=True, limit_choices_to={'is_agriculteur': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mes_livreurs', to=settings.AUTH_USER_MODEL, verbose_name='Agriculteur')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livreur_profile', to=settings.AUTH_USER_MODEL, verbose_name='Compte livreur')),
            ],
        ),
    ]
