# Generated by Django 4.2.21 on 2025-05-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_deliveryperson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryperson',
            options={'verbose_name': 'Livreur', 'verbose_name_plural': 'Livreurs'},
        ),
    ]
