# Generated by Django 4.2.21 on 2025-06-06 20:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_deliveryperson_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerequest',
            options={'ordering': ['replacement'], 'verbose_name': "Demande d'échange", 'verbose_name_plural': "Demandes d'échange"},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['client'], 'verbose_name': 'Commande', 'verbose_name_plural': 'Commandes'},
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'ordering': ['code'], 'verbose_name': 'Code promo', 'verbose_name_plural': 'Codes promo'},
        ),
        migrations.AlterModelOptions(
            name='stockalert',
            options={'ordering': ['product'], 'verbose_name': 'Alerte de stock', 'verbose_name_plural': 'Alertes de stock'},
        ),
        migrations.AlterModelOptions(
            name='stocklevel',
            options={'ordering': ['id'], 'verbose_name': 'Niveau de stock', 'verbose_name_plural': 'Niveaux de stock'},
        ),
        migrations.RemoveField(
            model_name='exchangerequest',
            name='return_request',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0, message='Le pourcentage doit être ≥ 0.'), django.core.validators.MaxValueValidator(100, message='Le pourcentage doit être ≤ 100.')], verbose_name='% de remise'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='remise', to='api.product', verbose_name='Produit'),
        ),
        migrations.DeleteModel(
            name='ReturnRequest',
        ),
    ]
