# Generated by Django 4.2.21 on 2025-06-08 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_selectedproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockalert',
            options={'ordering': ['product', 'warehouse'], 'verbose_name': 'Alerte de stock', 'verbose_name_plural': 'Alertes de stock'},
        ),
        migrations.RemoveField(
            model_name='stockalert',
            name='user',
        ),
        migrations.AddField(
            model_name='stockalert',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.warehouse', verbose_name='Entrepôt'),
        ),
    ]
