# Generated by Django 4.2.21 on 2025-06-08 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_stockalert_options_remove_stockalert_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity_in_stock',
        ),
    ]
