# Generated by Django 4.2.21 on 2025-06-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_stockmovement_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='stock_applied',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='stocklevel',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantité en stock'),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('product', 'lot_number')},
        ),
    ]
