# Generated by Django 4.2.21 on 2025-06-16 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerequest',
            name='refund_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_request', to='api.refundrequest', verbose_name='Demande de remboursement liée'),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_requests', to='api.clientprofile'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Localisation'),
        ),
    ]
