# Generated by Django 4.2.21 on 2025-06-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_exchangerequest_refund_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='type',
            field=models.CharField(choices=[('LIVRAISON', 'Problème de livraison'), ('STOCK', 'Intervention stock'), ('REMBOURSEMENT', 'Suivi remboursement'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='verified_purchase',
            field=models.BooleanField(default=False, help_text="Indique si l'achat du produit a été vérifié.", verbose_name='Achat vérifié'),
        ),
    ]
